### ISSUE TITLE
Add instructions on how to install redis to the README.

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#102]

**Comment by jeffgerlach** [comment]
May not need this if we end up implementing #114

**Comment by kenmazaika** [comment]
We may want to switch this to be instructions to start the rails server.

```
rails s -b 0.0.0.0
```

We definitely don't need instructions to install redis anymore though.

**Comment by robertsapunarich** [comment]
I can do this. I missed the conversation on why this is the case though. Does it have to do with sucker punch?

**Comment by kenmazaika** [comment]
Doesn't have to do with suckerpunch.  Just because we upgraded rails, if you're on vagrant this command needs to run to start the server.
