### ISSUE TITLE
As a User, I should have the ability to add my github handle

### ISSUE THREAD

**Issue by amarkpark** [FirehoseCommunity/DEFCON#107]
Potentially in the User Dashboard?

**Comment by amarkpark** [comment]
This may be related to Issue https://github.com/FirehoseCommunity/DEFCON/issues/108 if someone decides to implement the [Github API](https://github.com/peter-murach/github)

**Comment by kenmazaika** [comment]
https://github.com/plataformatec/devise#strong-parameters

**Comment by NKHolton** [comment]
I'll admit I'm having trouble understanding where to start with this.  My original thought was just to run a migration to add the 'github_handle' field to the Users table then add the appropriate 'stuff' in application.html.haml where it looks like the other My Profile information is located.  With the Devise link you provided above, Ken, I don't understand how this is associated with Devise.  Isn't Devise just for user authentication/signing-in and out?  The github handle won't be something a user provides during registration, right?  Thx!

**Comment by kenmazaika** [comment]
On signing up, as a user, you should be able to enter your GitHub handle.  First step is to add the database field.  The second step is to add the fields to the form.

**Comment by NKHolton** [comment]
Ok, thanks, Ken.  As for the Registration page/view I can't find it.  Looked back in rake routes and went to localhost:3030/users/sign-in but there's only a sign-in option and no sign-up page from what I can see.  Am I missing something?

**Comment by kenmazaika** [comment]
Ah, right, we have an invite process. Checkout this file:

https://github.com/FirehoseCommunity/DEFCON/blob/master/app/views/admin/users/invitations/new.html.haml

**Comment by robertsapunarich** [comment]
Natalie - just sent you a message on slack. Want to pair on this? I'll be available shortly.

Sent from Outlook Mobile

On Tue, Mar 1, 2016 at 9:47 AM -0800, "ken mazaika" notifications@github.com wrote:

Ah, right, we have an invite process. Checkout this file:

https://github.com/FirehoseCommunity/DEFCON/blob/master/app/views/admin/users/invitations/new.html.haml

**Comment by NKHolton** [comment]
Maybe a silly question but can I go ahead and push my partial changes/branch to github.  I've done what I think to be most of the edits needed for this but not all.  Thx!

**Comment by NKHolton** [comment]
...and create a pull request I mean.

**Comment by Matt-Lepley** [comment]
Of course. As long as your branch is unique and not master feel free to push the branch to github and then make a PR with that branch.

**Comment by NKHolton** [comment]
Ok, thanks, Matt!

**Comment by Matt-Lepley** [comment]
Not a problem, and not a silly question. :)
