### ISSUE TITLE
Font colors should be adjusted for readability.

### ISSUE THREAD

**Issue by tylerpendleton** [FirehoseCommunity/DEFCON#112]
Dark text over dark backgrounds can be difficult to read.

![screen shot 2016-01-23 at 8 53 00 pm](https://cloud.githubusercontent.com/assets/10295376/12533993/bb9891c6-c213-11e5-8c77-633784656d1f.png)

**Comment by kenmazaika** [comment]
Awesome job, pointing out areas we can improve in the app, @tylerpendleton!

**Comment by VictoriaBrouard** [comment]
In addition to the above which I completed as part of Issue 127,  I can see there is black text on the black background on the User Dashboard too, but rather than change this, I don't think the text is needed at all.  I'll make a pull request to this effect.

**Comment by kenmazaika** [comment]
Perfect!
