### ISSUE TITLE
Posts Index Page Is off

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#127]
Right now, the posts index page looks like this:

![screen shot 2016-02-25 at 6 39 27 pm](https://cloud.githubusercontent.com/assets/233615/13338401/21eda4bc-dbef-11e5-847c-fb21e0d32613.png)

We should do the following:
- Remove the headline that is in black that says "Write a post".
- Remove the button that pops up the modal.
- Add to the topnav a button to "Add a new Post".  Clicking this will cause the modal to popup.

-> we're probably going to move the modal functionality from `app/views/posts/index.html.erb` into `app/views/layouts/application.html.erb`, so that the modal can be shown on any page.

**Comment by VictoriaBrouard** [comment]
Please see pull request.  I think I've acheived everything above.

**Comment by VictoriaBrouard** [comment]
Just a thought.... it wasn't in the brief but the view posts page also has the "Write a Post' button, so perhaps this should be removed too.

**Comment by kenmazaika** [comment]
Awesome!
