### ISSUE TITLE
First user has admin permissions

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#15]
Make it possible to create a new user, where the admin field is set to `true`.
- The first user that signs up should be defaulted to admin.
- I would suggest looking at the `before_save` callback in the model.

```
class User < ActiveRecord::Base
  before_save :check_if_admin

  def check_if_admin
    # custom logic can go here.
  end
end
```

That would create a user in our database table with the admin flag set to `true`.

**Comment by Matt-Lepley** [comment]
closed via: https://github.com/FirehoseCommunity/DEFCON/pull/26
