### ISSUE TITLE
Admins should be able to make other users admins

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#16]
Build a separate page that allows admins to grant permissions to other users on the platform and the refactor for Admin so there is a single `AdminController` that all admins stuff can go through.

**Comment by amarkpark** [comment]
@kenmazaika since this issue is closely related to the updates we discussed to the Rake task PR you just merged in the meeting would you like me to do this while I'm at it, or focus on the upvote system?

**Comment by kenmazaika** [comment]
Sure @amarkpark!! :)

**Comment by amarkpark** [comment]
@kenmazaika I see in the migration history that the admin column default was previously "false" but the default was removed (I'm guessing when the odd first user logic was added to make the first user an admin?)  Safe to assume I can re-add the default false value for users?  And is it important to write migrations so that they can be reversed?

**Comment by kenmazaika** [comment]
I think that is a logical thing to do. :+1:

**Comment by amarkpark** [comment]
BTW @kenmazaika I tried moving those Rake-specific methods into the User.rb Model but Rake couldn't call them when they were removed from the rakefile.  I thought that was what I had read/understood while researching.  Rake can use methods for DRY, but seems they're special methods inside the rakefile.

**Comment by amarkpark** [comment]
I'm trying to figure out if Admin pages should be subbed under an Admin folder the same way Instructor views were subbed under an Instructor folder in Flixter - separate controllers etc... @kenmazaika please advise?

**Comment by kenmazaika** [comment]
You should be able to move methods into the model so long as you use the `=> :environment` syntax when defining the task.

I like the idea of nesting admin stuff under the admin namespace a lot!

**Comment by amarkpark** [comment]
preliminary, not done yet: https://github.com/FirehoseCommunity/DEFCON/tree/amp/admins_promote_users_issue16

**Comment by amarkpark** [comment]
PR is up:
https://github.com/FirehoseCommunity/DEFCON/pull/64
REALLY needs styling but it is at least functional.
