### ISSUE TITLE
Write tests for the landing page that we have

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#17]
Controller test for the landing page that makes sure it doesn't give an error message.

**Comment by robertsapunarich** [comment]
I disabled fixtures in the test_helper and included test helpers for devise. Would adding the FactoryGirl gem for future tests be a good call?

**Comment by kenmazaika** [comment]
It's definitely a good call, but since it works with the models, we should probably hold off on doing that until #18 is resolved.
