### ISSUE TITLE
Full CRUD for Posts

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#18]
We should have a post database table and model.
- title
- body -> should be a text field, not a string.
- user_id
- we'll use created_at timestamp
## Actions
- new
- create
- edit
- update
- destroy

**Comment by kenmazaika** [comment]
To create a new post, make a modal on the index page.  Edit will have it's own page.

**Comment by Matt-Lepley** [comment]
Issue closed via: https://github.com/FirehoseCommunity/DEFCON/pull/30
