### ISSUE TITLE
Setup continuous integration

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#19]
Either with CodeShip or TravisCI.

Advice from Colin:

> Just go with CodeShip

**Comment by kenmazaika** [comment]
- Need to add user accounts to codeship.

**Comment by colinrubbert** [comment]
Firehose Project / Lightning talk video on setting up [Codeship](https://www.youtube.com/watch?v=iXCEqTfq9xw).

**Comment by amarkpark** [comment]
@Matt-Lepley Thanks for the invite/add I am able to view the project in codeship now.  Can potentially close this issue?  (or make it DEFCON 5?) ;-) Not sure what the internal protocol is here.

**Comment by kenmazaika** [comment]
Nice!  Let's close this ticket! :) :+1:
