### ISSUE TITLE
As an admin I should be able to invite users

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#21]
There should be a page where admins can invite a user.  Inviting someone will require their email address -> and it will create a user in the database with no password (or set it with a temporary password, with `SecureRandom.hex`).

Then, the user can be sent to the password reset flow, and then be a valid user who can login and do stuff.

**Comment by kenmazaika** [comment]
The email will come from the address:

```
no-reply@thefirehoseproject.com
```

**Comment by robertsapunarich** [comment]
Do you think using DeviseInvitable would be a good call? Trying to think of the best way to go about this. https://github.com/scambra/devise_invitable

**Comment by kenmazaika** [comment]
I wasn't aware of this gem.  Feel free to give it a shot!  If it proves to be a pain, we can always write it by hand.
