### ISSUE TITLE
Fix the Top Nav

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#38]

**Comment by amarkpark** [comment]
Is this about the navbar-nav right not pulling to the right?

**Comment by ceceliahavens** [comment]
I think it is about hooking up the links, which I did already, but it might be about the spacing issue.  I honestly don't remember.

**Comment by kenmazaika** [comment]
The navbar used to be broken a bit.  There were links in the navbar overhanging and they weren't styled like navbar links, but blue like regular links.  This issue may be fixed now.
