### ISSUE TITLE
Logging in turns users' admin flag to false

### ISSUE THREAD

**Issue by jeffgerlach** [FirehoseCommunity/DEFCON#47]
Currently if you make a single user, their admin flag is set to true. But then when you log into the site, their sign in attributes are updated, which calls the before_save action (check_if_first_user) and sets the admin flag to false....and since there is a user in the database, it can never be set back to true.

**Comment by kenmazaika** [comment]
I believe @amarkpark was working to remove the whole "first user is an admin" functionality.  In the process, that should fix the problem.

**Comment by amarkpark** [comment]
Hey grab the current Master branch and see if the PR Ken merged earlier fixes the issue?

**Comment by jeffgerlach** [comment]
Looks like #49 did indeed fix this bug. Awesome work @amarkpark!
