### ISSUE TITLE
Deploy the code live to Heroku

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#5]
As a member of the team we should be able to deploy to heroku.

In order to do that, whoever sets up the heroku app needs to add people by their email address:

Emails: `kenmazaika@gmail.com`, `lepley.matt@gmail.com`, `robertsapunarich@gmail.com`

**Comment by Matt-Lepley** [comment]
- Deployed code to heroku (http://firehose-defcon.herokuapp.com/)
- Added Ken and Robert as collaborators

Edit: Changed to firehose-defcon to be more consistent with naming
