### ISSUE TITLE
Posts should be emailed out to everyone with comment_notification true

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#58]
We currently have a boolean field that users use to indicate they want to be emailed notifications.  We have the notification mailer in a separate ticket.  This ticket is to glue those two pieces together.

**Comment by jeffgerlach** [comment]
So there are actually 2 notification Boolean fields, one to be notified of new posts and one for notifications of comments on the users' posts. Assuming we want to start off addressing the first case (for new posts)?

**Comment by kenmazaika** [comment]
That makes sense.  Thanks for clarifying, @jeffgerlach.

**Comment by nicolaguidi** [comment]
Addressed in #77.
I wasn't able to write enough tests as I wanted to. I also added `pry-byebug`.
