### ISSUE TITLE
The date format on the index page is weird

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#61]
Let's use a better format for it.

![screen shot 2016-01-07 at 6 40 39 pm](https://cloud.githubusercontent.com/assets/233615/12186188/3c7024b0-b56e-11e5-8ae6-e07bbe40ce6a.png)

**Comment by nicolaguidi** [comment]
Addressed in #75 
For posts we could also use something like 'Posted X minutes/hours/days ago'...

**Comment by kenmazaika** [comment]
@nicolaguidi I love the idea.  Just like instagram!

![screen shot 2016-01-11 at 7 28 22 pm](https://cloud.githubusercontent.com/assets/233615/12251024/84b79784-b899-11e5-8a97-1089f25a8db5.png)
