### ISSUE TITLE
Background defined in master.css.scss not saved into assets folder

### ISSUE THREAD

**Issue by jeffgerlach** [FirehoseCommunity/DEFCON#65]
On line #34 of master.css.scss there is a reference to a 'crossword.png' which I think just got left out of a commit. Should be an easy fix! (just noticed a bunch of errors in the server log/browser console)

**Comment by ceceliahavens** [comment]
I'm not sure who uploaded the original file, but I will replace it with something else to get the bug resolved.

**Comment by ceceliahavens** [comment]
issue resolved when I styled the index page, I assigned a different background and took out the crossword.png. I did find the original file in suptlepatterns and upload it in case we want to bring it back. It is a very soft subtle white background.
