### ISSUE TITLE
WYSIWYG editor not fully enabled in my Chrome session locally

### ISSUE THREAD

**Issue by amarkpark** [FirehoseCommunity/DEFCON#67]
I can't currently log in to the herokuapp page to see if it works the same way there. The following screenshot shows the post editor without any editing controls:
![screen shot 2016-01-08 at 2 37 25 am](https://cloud.githubusercontent.com/assets/13741014/12194079/a1c9a9f0-b5b2-11e5-96b1-d44364b4b147.png)

I recall using Sharepoint I would run in to this issue of no editor controls visible when I tried to post using any browser other than IE. I read the pagedown-bootstrap-rails readme and I don't see any browser incompatibility listed... anybody else find the post WYSIWYG controls don't come up in a specific browser?

**Comment by ceceliahavens** [comment]
I pulled this up in Chrome and Firefox and saw the appropriate markdown editor with both browsers.

**Comment by kenmazaika** [comment]
Awesome!  Thanks, @ceceliahavens! :) :+1:
