### ISSUE TITLE
The post should show how long ago the post was made.

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#76]
If it has been posted less than an hour ago, it should say "Posted x Minutes Ago".  If it's under 24 hours is should say "Post x Hours Ago".  Otherwise it should say "Posted X days ago".  Similar to Instagram.

![screen shot 2016-01-11 at 7 28 22 pm](https://cloud.githubusercontent.com/assets/233615/12251052/b5b305e4-b899-11e5-8e20-6c1d60293adc.png)

**Comment by jeffgerlach** [comment]
Addressed in #78.
