### ISSUE TITLE
Notification Mailer Can Be Optimized

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#81]
Right now we're looping through each user and delivering an email to them individually.  If we have 100 people who receive the post and it takes 1 second to send each email, that means it would take 100 seconds, or almost 2 minutes for the request to happen.

This is a good opportunity to use background tasks, such as SideKiq to perform the tasks asynchronously, so the emails will go out after the user is redirected to the main page.

**Comment by jeffgerlach** [comment]
Addressed in #114
