### ISSUE TITLE
Editing Posts and Comments do not use the WYSIWYG editor.

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#84]
If you click on the edit button for a comment, you are brought to a standard html form, not the WYSIWYG editor. Same (i think) for post updates.

**Comment by ceceliahavens** [comment]
I updated these, however I notice there is no clickable button to take you to edit posts, and there was no styling when you manually typed the link. I went ahead and added a booyah box to match the other pages for the posts/edit but I think we can make another ticket for the edit buttons for posts.
