### ISSUE TITLE
Create Seeds.rb file

### ISSUE THREAD

**Issue by colinrubbert** [FirehoseCommunity/DEFCON#9]
#### Create `db/seeds.rb` file

Once devise and any other user sign up features are implemented, create a seeds.rb file to have a base database of users and content that anyone who joins the project or wants to contribute at a later date can easily populate the database with information.

**Comment by amarkpark** [comment]
When I populate the Seeds.rb should I do it A) with static data: EX: create a generic admin user with a fake email address... Or B) customizable data and instructions in the Readme on appropriate use for the Seeds.rb? ED: seed admin user but ask developers to <insert your valid email here><password here> before running the rake db:seed task so they can have their own functional mail etc... Or C) a hybrid where I start with generic fake data and urge developers to input their own data.

Options A and C make the former security-conscious IT person in me really twitchy.  Do I need to be concerned with security at this stage?

**Comment by kenmazaika** [comment]
I don't think we should create the admin user through the seeds file.  Instead I think we may want to build a custom rake task, such that running:

```
rake data:make_admin EMAIL=ken@thefirehoseproject.com
```

Would make me an admin.  Just my 2 cents.

**Comment by amarkpark** [comment]
On it

**Comment by amarkpark** [comment]
This is addressed in PR: https://github.com/FirehoseCommunity/DEFCON/pull/33

@kenmazaika the syntax of the implementation is a bit different than your suggestion, I put use guidelines in the PR notes. I'd be happy to add them to the Readme or anywhere else FHP likes to document.

**Comment by amarkpark** [comment]
PR https://github.com/FirehoseCommunity/DEFCON/pull/96
